---
#title: "Einführung in R - Programmieren für Geisteswissenschaften"
output: html_document
---

## Einführung in R - Programmieren für Geisteswissenschaften

Diese Website dokumentiert die Inhalte des Tutoriums **["Einführung in R — Programmieren für die Geisteswissenschaften"](https://www.fu-berlin.de/vv/de/lv/734035)** an der FU Berlin im Sommersemester 2022. Das Tutorium richtet sich an Studierende insbesondere der Literatur- und Geschichtswissenschaften.

Die Skripte und Lösungen zu den Übungen befinden sich im GitHub-Repository [lipogg/r-tutorium](https://github.com/lipogg/r-tutorium). Für Nachnutzer:innen ohne Zugang zum Repository sind alle Skripte zusätzlich zum direkten Download verlinkt. 

#### Sitzungen:

----------------
**[Sitzung 1 - Basics](tutorium1_250422_basics.html)** 

**[Sitzung 2 - Daten und Dateien](tutorium2_020522_dateien.html)**

**[Sitzung 3 - Reguläre Ausdrücke](tutorium3_09052022_regex.html)**

**[Sitzung 4 - XML und TEI](tutorium4_16052022_xml.html)**

**[Sitzung 5 - Git und GitHub](tutorium5_230522_github.html)**

**[Sitzung 6 - Stilometrie](tutorium6_130622_stilometrie.html)**

**[Sitzung 7 - Virtuelle Umgebungen](tutorium7_200622_virtuelle_umgebungen.html)**

**[Sitzung 8 - Web Scraping und APIs](tutorium8_27062022_webscraping.html)**

**[Sitzung 9 - Quantitative Textanalyse](tutorium9_04072022_textanalyse.html)**

**[Sitzung 10 - Netzwerkanalyse](tutorium10_11072022_netzwerke.html)**

